# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    tags: v.*

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            FILE_NAME: MazeGen
          
          - os: windows-latest
            FILE_NAME: MazeGen.exe
          
          - os: macos-latest
            FILE_NAME: MazeGen
      

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install poetry
      run: pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Create build
      run: poetry run invoke build
    - name: Upload build
      uses: svenstaro/upload-release-action@v2
      with:
        file: dist/${{ FILE_NAME }}
      
