name: Build an executable and upload to release

on:
  push:
    tags: v*

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            SRC_FILE_NAME: MazeGen
            DEST_FILE_NAME: MazeGen_Linux
          
          - os: windows-latest
            SRC_FILE_NAME: MazeGen.exe
            DEST_FILE_NAME: MazeGen_Windows.exe
          
          - os: macos-latest
            SRC_FILE_NAME: MazeGen
            DEST_FILE_NAME: MazeGen_Mac
      

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install poetry
      run: pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Create build
      run: poetry run invoke build
    - name: Upload build
      uses: svenstaro/upload-release-action@v2
      with:
        file: dist/${{ matrix.SRC_FILE_NAME }}
        asset_name: ${{ matrix.DEST_FILE_NAME }}
